### ISSUE TITLE
Active: Jacks enters Evasion, a defensive stance, for up to 2 seconds, causing all basic attacks against him to miss. Jacks also takes 25% reduced damage from all area of effect abilities. 

### ISSUE THREAD

**Issue by tankirules** [XenocidePC/xenobot#1]
Active: Jacks enters Evasion, a defensive stance, for up to 2 seconds, causing all basic attacks against him to miss. Jacks also takes 25% reduced damage from all area of effect abilities.

**Comment by XenocidePC** [comment]
😆
